# Generated by Django 5.0.1 on 2024-02-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210321_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_medium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
