# Generated by Django 5.0.1 on 2024-02-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_price_large_product_price_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(related_name='product_variations', to='store.variation'),
        ),
    ]
