# Generated by Django 3.1 on 2024-01-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='url',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
