# Generated by Django 3.1 on 2024-01-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categery', '0002_auto_20240106_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='url',
            new_name='slug',
        ),
    ]
