# Generated by Django 3.1 on 2024-01-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categery', '0003_auto_20240106_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='photos/category'),
        ),
    ]
