# Generated by Django 5.0.1 on 2024-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201006_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_heading', models.CharField(blank=True, max_length=100)),
                ('ban_image', models.ImageField(blank=True, upload_to='banner')),
            ],
        ),
    ]
